const PersianTextArray = [
  "از همین امروز شروع کن فردا دیره",
  "با کسی بگرد که میخوای شبیه اون بشی",
  "آدمای بی ارزش رو قیچی کن",
  "هیچوقت نگو نمیتونم",
];
const EnglishTextArray = [
  "Start today, don't wait for tomorrow.",
  "Surround yourself with those you aspire to become.",
  "Cut out the negative influences from your life.",
  "Never say 'I can't.'",
  "Believe in your abilities and potential.",
  "Every small step counts towards a big achievement.",
  "Embrace challenges as opportunities for growth.",
  "Your success is determined by your daily habits.",
  "Learn from failures; they are stepping stones to success.",
  "Set clear goals and work towards them with determination.",
  "Success is not a destination; it's a journey.",
  "Stay focused on your vision and ignore distractions.",
  "Celebrate your progress, no matter how small.",
  "Take risks, and don't fear stepping out of your comfort zone.",
  "Surround yourself with positivity and optimistic people.",
  "Your attitude determines your altitude in life.",
  "Visualize your success and work towards that vision.",
  "Continuous learning is the key to staying ahead.",
  "Success is the sum of small efforts repeated daily.",
  "Stay persistent; success often comes after perseverance.",
  "Believe in the power of consistency.",
  "Challenge yourself to become better every day.",
  "Don't be afraid of change; embrace it for growth.",
  "Success is not about luck; it's about hard work and dedication.",
  "Invest in self-improvement; you are your best asset.",
  "Surround yourself with positivity and let go of negativity.",
  "Your mindset determines your outcome.",
  "Dream big, work hard, stay focused.",
  "Success is a journey of overcoming obstacles.",
  "Don't compare your chapter 1 to someone else's chapter 20.",
  "Stay true to yourself and your values.",
  "Celebrate the success of others; it attracts positivity.",
  "Be adaptable; change is the only constant.",
  "Your potential is limitless; believe in yourself.",
  "Success is not about the destination; it's about the journey.",
  "Challenge yourself to go beyond your limits.",
  "Success is the result of preparation, hard work, and learning.",
  "Create a vision that makes you want to jump out of bed in the morning.",
  "Your time is now; don't wait for the perfect moment.",
  "Stay positive, work hard, make it happen.",
  "Every setback is a setup for a comeback.",
  "Success is not final, failure is not fatal; it's the courage to continue that counts.",
  "The only limit to your impact is your imagination and commitment.",
  "Dream it. Believe it. Achieve it.",
  "You are stronger than you think, more capable than you imagine.",
  "The only way to do great work is to love what you do.",
  "Don't watch the clock; do what it does. Keep going.",
  "Success is not in what you have, but who you are.",
  "Your potential is like a seed; it needs nurturing to grow.",
  "Stay committed to your goals, but flexible in your approach.",
];
// Arabic
const ArabicTextArray = [
  "ابدأ اليوم بإيجابية، وليس غدًا.",
  "تفاءل وابحث عن الفرص في كل تحدي.",
  "قم بالأشياء التي تجعل قلبك ينبض بالسعادة.",
  "كن قويًا في وجه الصعوبات، فإنها ستمر.",
  "لا تخف من المستقبل، صنعه بإيجابية اليوم.",
  "تحدى نفسك لتحقيق الأهداف الكبيرة.",
  "استمر في النمو وتطوير ذاتك بشكل يومي.",
  "الإصرار يحقق المستحيل، فحافظ على تحقيق أحلامك.",
  "كن دائمًا نشيطًا وابتعد عن الكسل.",
  "تخلص من الشك واستبدله بالإيمان بقدراتك.",
  "التحديات هي فرص للتعلم والنمو.",
  "عش حياة تعطيك السعادة والرضا الدائم.",
  "ابنِ الجسر حينما تواجه العقبات.",
  "اعمل بجد ولا تتوقف أبدًا عن التحسن.",
  "كل تجربة فاشلة هي خطوة قريبة نحو النجاح.",
  "تصبح قويًا عندما تكون ضعيفًا، هذا هو النجاح.",
  "ابنِ أحلامك بأفعالك اليومية.",
  "التفاؤل هو المفتاح إلى حياة سعيدة ومثمرة.",
  "التقدم يحتاج إلى تفكير إيجابي وعزيمة قوية.",
  "تحدي نفسك وتفوق عن توقعاتك.",
  "الابتسامة تكسب القلوب وتفتح الأبواب.",
  "استمتع بكل لحظة وحقق قيمة منها.",
  "تعلم من الأمس وعش لليوم وأمل في الغد.",
  "النجاح يبدأ بخطوة صغيرة وثقة كبيرة.",
  "تحدث بالتفاؤل واجعل الآخرين يتشجعون.",
  "اجعل هدفك هو دافعك للتفوق يوميًا.",
  "الثقة بالنفس تساعدك على تحقيق المستحيل.",
  "اعتني بنفسك بدنيًا وعقليًا وروحيًا.",
  "قدرتك على التحمل تحدد نجاحك في الحياة.",
  "ابنِ جسراً من الأمل لكل من حولك.",
  "النجاح هو النتيجة المباشرة للعمل الجاد.",
  "كن كالشمس، تشرق بإشراقها الخاصة.",
  "لا تخجل من الفشل، بل استفد منه وارتقِ.",
  "كن إيجابيًا واصنع تأثيرًا إيجابيًا في العالم.",
  "الأمل هو الضوء الذي يبقى مضيئًا في الظلام.",
  "العمل الجماعي يحقق أهدافًا كبيرة.",
  "ابذل قصارى جهدك ولا تتراجع أبدًا.",
  "التحفيز يأتي من الداخل وينبع من الرغبة الحقيقية.",
  "الاستمرارية في التطوير تجعل الحياة أفضل.",
  "تعلم من أخطائك ولا تكن ممن يستسلمون.",
  "الابتسامة تغنيك عن الكثير من الكلمات.",
  "التفكير الإيجابي يخلق حياة إيجابية.",
  "النجاح يبدأ برؤية وهدف واضح.",
  "كن شمعة تنير في ظلام الصعاب.",
  "لا تخف من المحاولة والفشل؛ فهي جزء من النجاح.",
  "التواصل الجيد يبني جسورًا قوية في العلاقات.",
  "تحدث بإيجابية وكن صاحب تأثير إيجابي على الآخرين.",
  "النجاح هو مجرد قرار يومي بالتحسن المستمر.",
  "عش بشغف وتفاؤل وستحقق النجاح.",
];
// French
const FrenchTextArray = [
  "Commencez aujourd'hui, n'attendez pas demain.",
  "Entourez-vous de ceux que vous aspirez à devenir.",
  "Éliminez les influences négatives de votre vie.",
  "Ne dites jamais 'Je ne peux pas'.",
  "Croyez en vos capacités et votre potentiel.",
  "Chaque petit pas compte pour une grande réalisation.",
  "Acceptez les défis comme des opportunités de croissance.",
  "Votre succès dépend de vos habitudes quotidiennes.",
  "Apprenez des échecs; ce sont des marches vers le succès.",
  "Fixez des objectifs clairs et travaillez-y avec détermination.",
  "Le succès n'est pas une destination; c'est un voyage.",
  "Restez concentré sur votre vision et ignorez les distractions.",
  "Célébrez vos progrès, peu importe leur ampleur.",
  "Prenez des risques et n'ayez pas peur de sortir de votre zone de confort.",
  "Entourez-vous de positivité et de personnes optimistes.",
  "Votre attitude détermine votre altitude dans la vie.",
  "Visualisez votre succès et travaillez vers cette vision.",
  "L'apprentissage continu est la clé pour rester en avance.",
  "Le succès est la somme de petits efforts répétés quotidiennement.",
  "Restez persévérant; le succès vient souvent après la persévérance.",
  "Croyez en la puissance de la cohérence.",
  "Challenges pour devenir meilleur chaque jour.",
  "N'ayez pas peur du changement; adoptez-le pour la croissance.",
  "Le succès n'est pas une question de chance; c'est le fruit du travail acharné et de la dévotion.",
  "Investissez dans l'amélioration de soi; vous êtes votre meilleur atout.",
  "Entourez-vous de positivité et éloignez-vous de la négativité.",
  "Votre mentalité détermine votre résultat.",
  "Rêvez grand, travaillez dur, restez concentré.",
  "Le succès est un voyage de surmonter les obstacles.",
  "Ne comparez pas votre chapitre 1 à celui de quelqu'un d'autre chapitre 20.",
  "Restez fidèle à vous-même et à vos valeurs.",
  "Célébrez le succès des autres; cela attire la positivité.",
  "Soyez adaptable; le changement est la seule constante.",
  "Votre potentiel est illimité; croyez en vous-même.",
  "Le succès n'est pas dans ce que vous avez, mais dans qui vous êtes.",
  "Votre potentiel est comme une graine; il a besoin de soins pour grandir.",
  "Restez fidèle à vos objectifs, mais soyez flexible dans votre approche.",
  "Le succès est dans ce que vous faites, pas dans ce que vous avez.",
  "Ne regardez pas la montre; faites ce qu'elle fait. Continuez.",
  "Le succès n'est pas dans ce que vous avez, mais dans qui vous êtes.",
  "Votre potentiel est comme une graine; il a besoin de soins pour grandir.",
  "Restez fidèle à vos objectifs, mais soyez flexible dans votre approche.",
  "Le succès est dans ce que vous faites, pas dans ce que vous avez.",
  "Ne regardez pas la montre; faites ce qu'elle fait. Continuez.",
  "Le succès n'est pas dans ce que vous avez, mais dans qui vous êtes.",
  "Votre potentiel est comme une graine; il a besoin de soins pour grandir.",
  "Restez fidèle à vos objectifs, mais soyez flexible dans votre approche.",
  "Le succès est dans ce que vous faites, pas dans ce que vous avez.",
  "Ne regardez pas la montre; faites ce qu'elle fait. Continuez.",
  "Le succès n'est pas dans ce que vous avez, mais dans qui vous êtes.",
  "Votre potentiel est comme une graine; il a besoin de soins pour grandir.",
  "Restez fidèle à vos objectifs, mais soyez flexible dans votre approche.",
  "Le succès est dans ce que vous faites, pas dans ce que vous avez.",
  "Ne regardez pas la montre; faites ce qu'elle fait. Continuez.",
];
// Spanish
const SpanishTextArray = [
  "Comienza hoy, no esperes a mañana.",
  "Rodeate de aquellos a quienes aspiras a ser.",
  "Elimina las influencias negativas de tu vida.",
  "Nunca digas 'No puedo'.",
  "Cree en tus capacidades y tu potencial.",
  "Cada pequeño paso cuenta para un gran logro.",
  "Acepta los desafíos como oportunidades de crecimiento.",
  "Tu éxito depende de tus hábitos diarios.",
  "Aprende de los fracasos; son escalones hacia el éxito.",
  "Establece objetivos claros y trabaja hacia ellos con determinación.",
  "El éxito no es un destino; es un viaje.",
  "Mantente enfocado en tu visión e ignora las distracciones.",
  "Celebra tus progresos, no importa cuán pequeños sean.",
  "Arriésgate y no temas salir de tu zona de confort.",
  "Rodeate de positividad y personas optimistas.",
  "Tu actitud determina tu altitud en la vida.",
  "Visualiza tu éxito y trabaja hacia esa visión.",
  "El aprendizaje continuo es la clave para mantenerse adelante.",
  "El éxito es la suma de pequeños esfuerzos repetidos a diario.",
  "Mantente persistente; el éxito a menudo viene después de la perseverancia.",
  "Cree en el poder de la consistencia.",
  "Desafíos para mejorar cada día.",
  "No tengas miedo del cambio; acéptalo para el crecimiento.",
  "El éxito no es cuestión de suerte; es el resultado del trabajo duro y la dedicación.",
  "Invierte en la mejora personal; eres tu mejor activo.",
  "Rodeate de positividad y deja ir la negatividad.",
  "Tu mentalidad determina tu resultado.",
  "Sueña en grande, trabaja duro, mantente enfocado.",
  "El éxito es un viaje de superar obstáculos.",
  "No compares tu capítulo 1 con el capítulo 20 de otra persona.",
  "Mantente fiel a ti mismo y a tus valores.",
  "Celebra el éxito de los demás; atrae la positividad.",
  "Sé adaptable; el cambio es la única constante.",
  "Tu potencial es ilimitado; cree en ti mismo.",
  "El éxito no está en lo que tienes, sino en quién eres.",
  "Tu potencial es como una semilla; necesita cuidados para crecer.",
  "Mantente comprometido con tus objetivos, pero flexible en tu enfoque.",
  "El éxito está en lo que haces, no en lo que tienes.",
  "No mires el reloj; haz lo que hace. Sigue adelante.",
  "El éxito no está en lo que tienes, sino en quién eres.",
  "Tu potencial es como una semilla; necesita cuidados para crecer.",
  "Mantente comprometido con tus objetivos, pero flexible en tu enfoque.",
  "El éxito está en lo que haces, no en lo que tienes.",
  "No mires el reloj; haz lo que hace. Sigue adelante.",
  "El éxito no está en lo que tienes, sino en quién eres.",
  "Tu potencial es como una semilla; necesita cuidados para crecer.",
  "Mantente comprometido con tus objetivos, pero flexible en tu enfoque.",
  "El éxito está en lo que haces, no en lo que tienes.",
  "No mires el reloj; haz lo que hace. Sigue adelante.",
];
// German
const GermanTextArray = [
  "Beginne heute, warte nicht auf morgen.",
  "Umgebe dich mit denen, die du werden möchtest.",
  "Schneide negative Einflüsse aus deinem Leben heraus.",
  "Sage niemals 'Ich kann nicht'.",
  "Glaube an deine Fähigkeiten und dein Potenzial.",
  "Jeder kleine Schritt zählt für einen großen Erfolg.",
  "Akzeptiere Herausforderungen als Chancen zum Wachsen.",
  "Dein Erfolg hängt von deinen täglichen Gewohnheiten ab.",
  "Lerne aus Fehlern; sie sind Stufen zum Erfolg.",
  "Setze klare Ziele und arbeite mit Entschlossenheit daran.",
  "Erfolg ist keine Destination; es ist eine Reise.",
  "Bleibe fokussiert auf deine Vision und ignoriere Ablenkungen.",
  "Feiere deine Fortschritte, egal wie klein sie sind.",
  "Riskiere und fürchte dich nicht davor, aus deiner Komfortzone auszubrechen.",
  "Umgebe dich mit Positivität und optimistischen Menschen.",
  "Deine Einstellung bestimmt deine Höhe im Leben.",
  "Visualisiere deinen Erfolg und arbeite auf diese Vision hin.",
  "Kontinuierliches Lernen ist der Schlüssel, um voraus zu bleiben.",
  "Erfolg ist die Summe kleiner täglicher Anstrengungen.",
  "Bleibe hartnäckig; Erfolg kommt oft nach Ausdauer.",
  "Glaube an die Kraft der Kontinuität.",
  "Herausforderungen für tägliches Wachstum.",
  "Hab keine Angst vor Veränderungen; nimm sie an und wachse daran.",
  "Erfolg ist keine Frage des Glücks; es ist das Ergebnis harter Arbeit und Hingabe.",
  "Investiere in Selbstverbesserung; du bist dein bestes Kapital.",
  "Umgebe dich mit Positivität und lass Negativität los.",
  "Deine Denkweise bestimmt dein Ergebnis.",
  "Träume groß, arbeite hart, bleibe fokussiert.",
  "Erfolg ist eine Reise, Hindernisse zu überwinden.",
  "Vergleiche dein Kapitel 1 nicht mit dem Kapitel 20 anderer Menschen.",
  "Bleibe dir selbst und deinen Werten treu.",
  "Feiere den Erfolg anderer; das zieht Positivität an.",
  "Sei anpassungsfähig; Veränderung ist die einzige Konstante.",
  "Dein Potenzial ist grenzenlos; glaube an dich selbst.",
  "Erfolg liegt nicht darin, was du hast, sondern wer du bist.",
  "Dein Potenzial ist wie ein Samen; er braucht Pflege, um zu wachsen.",
  "Bleibe deinen Zielen treu, aber sei flexibel in deinem Ansatz.",
  "Erfolg liegt darin, was du tust, nicht darin, was du hast.",
  "Sieh nicht auf die Uhr; mach weiter, was sie macht.",
  "Erfolg liegt nicht darin, was du hast, sondern wer du bist.",
  "Dein Potenzial ist wie ein Samen; er braucht Pflege, um zu wachsen.",
  "Bleibe deinen Zielen treu, aber sei flexibel in deinem Ansatz.",
  "Erfolg liegt darin, was du tust, nicht darin, was du hast.",
  "Sieh nicht auf die Uhr; mach weiter, was sie macht.",
  "Erfolg liegt nicht darin, was du hast, sondern wer du bist.",
  "Dein Potenzial ist wie ein Samen; er braucht Pflege, um zu wachsen.",
  "Bleibe deinen Zielen treu, aber sei flexibel in deinem Ansatz.",
  "Erfolg liegt darin, was du tust, nicht darin, was du hast.",
  "Sieh nicht auf die Uhr; mach weiter, was sie macht.",
];
// Russian
const RussianTextArray = [
  "Начни сегодня, не жди завтра.",
  "Окружай себя теми, кем ты хочешь стать.",
  "Избавься от негативных влияний в своей жизни.",
  "Никогда не говори 'Я не могу'.",
  "Верь в свои способности и потенциал.",
  "Каждый маленький шаг важен для большого достижения.",
  "Принимай вызовы как возможности для роста.",
  "Твой успех зависит от твоих ежедневных привычек.",
  "Извлекай уроки из неудач; они являются ступеньками к успеху.",
  "Ставь четкие цели и работай над ними с решимостью.",
  "Успех — не место назначения; это путь.",
  "Оставайся фокусированным на своей цели, игнорируя отвлечения.",
  "Празднуй свой прогресс, несмотря на его масштаб.",
  "Рискуй и не бойся выходить из зоны комфорта.",
  "Окружай себя положительностью и оптимистичными людьми.",
  "Твое отношение определяет твой уровень в жизни.",
  "Визуализируй свой успех и работай в направлении этой цели.",
  "Постоянное обучение — ключ к сохранению лидерства.",
  "Успех — это сумма малых усилий, повторяемых ежедневно.",
  "Оставайся настойчивым; успех часто приходит после упорства.",
  "Верь в силу последовательности.",
  "Сталкивайся с вызовами, чтобы стать лучше каждый день.",
  "Не бойся перемен; прими их для роста.",
  "Успех — не в везении; это результат труда и посвящения.",
  "Инвестируй в личное развитие; ты свой лучший актив.",
  "Окружай себя положительностью и избавься от негатива.",
  "Твоя ментальность определяет результат.",
  "Мечтай крупно, работай усердно, оставайся сосредоточенным.",
  "Успех — это путь преодоления преград.",
  "Не сравнивай свою главу 1 с главой 20 другого человека.",
  "Оставайся верным себе и своим ценностям.",
  "Празднуй успехи других; это привлекает позитивность.",
  "Будь гибким; изменение — единственная постоянная.",
  "Твой потенциал неограничен; верь в себя.",
  "Успех — это не в том, что у тебя есть, а в том, кто ты.",
  "Твой потенциал как семечко; ему нужны заботы, чтобы расти.",
  "Оставайся преданным своим целям, но гибким в подходе.",
  "Успех в том, что ты делаешь, не в том, что у тебя есть.",
  "Не смотри на часы; делай то, что они делают. Продолжай двигаться.",
  "Успех не в том, что у тебя есть, а в том, кто ты.",
  "Твой потенциал как семечко; ему нужны заботы, чтобы расти.",
  "Оставайся преданным своим целям, но гибким в подходе.",
  "Успех в том, что ты делаешь, не в том, что у тебя есть.",
  "Не смотри на часы; делай то, что они делают. Продолжай двигаться.",
  "Успех не в том, что у тебя есть, а в том, кто ты.",
];
// Portuguese
const PortugueseTextArray = [
  "Comece hoje, não espere pelo amanhã.",
  "Cerque-se daqueles que você aspira ser.",
  "Elimine as influências negativas da sua vida.",
  "Nunca diga 'Eu não posso'.",
  "Acredite nas suas habilidades e potencial.",
  "Cada pequeno passo conta para uma grande conquista.",
  "Aceite os desafios como oportunidades de crescimento.",
  "Seu sucesso depende dos seus hábitos diários.",
  "Aprenda com os fracassos; são degraus para o sucesso.",
  "Estabeleça metas claras e trabalhe nelas com determinação.",
  "O sucesso não é um destino; é uma jornada.",
  "Mantenha o foco na sua visão e ignore as distrações.",
  "Celebre seu progresso, por menor que seja.",
  "Arrisque-se e não tema sair da sua zona de conforto.",
  "Cerque-se de positividade e de pessoas otimistas.",
  "Sua atitude determina sua altitude na vida.",
  "Visualize seu sucesso e trabalhe na direção dessa visão.",
  "A aprendizagem contínua é a chave para se manter à frente.",
  "O sucesso é a soma de pequenos esforços repetidos diariamente.",
  "Mantenha a persistência; o sucesso muitas vezes vem após a perseverança.",
  "Acredite no poder da consistência.",
  "Desafie-se a se tornar melhor a cada dia.",
  "Não tenha medo da mudança; abrace-a para crescer.",
  "O sucesso não é sobre sorte; é sobre trabalho árduo e dedicação.",
  "Invista no autodesenvolvimento; você é seu melhor ativo.",
  "Cerque-se de positividade e deixe para trás a negatividade.",
  "Sua mentalidade determina seu resultado.",
  "Sonhe grande, trabalhe duro, mantenha o foco.",
  "O sucesso é uma jornada de superação de obstáculos.",
  "Não compare seu capítulo 1 com o capítulo 20 de outra pessoa.",
  "Mantenha-se fiel a si mesmo e aos seus valores.",
  "Celebre o sucesso dos outros; isso atrai positividade.",
  "Seja adaptável; a mudança é a única constante.",
  "Seu potencial é ilimitado; acredite em si mesmo.",
  "O sucesso não é sobre o destino; é sobre a jornada.",
  "Desafie-se a ir além de seus limites.",
  "O sucesso é o resultado de preparação, trabalho árduo e aprendizado.",
  "Crie uma visão que faça você querer pular da cama de manhã.",
  "Sua hora é agora; não espere pelo momento perfeito.",
  "Mantenha-se positivo, trabalhe duro, faça acontecer.",
  "Cada revés é uma preparação para um retorno.",
  "O sucesso não é definitivo, o fracasso não é fatal; é a coragem de continuar que conta.",
  "O único limite para seu impacto é sua imaginação e comprometimento.",
  "Sonhe. Acredite. Alcance.",
  "Você é mais forte do que pensa, mais capaz do que imagina.",
  "A única maneira de fazer um grande trabalho é amar o que você faz.",
  "Não olhe para o relógio; faça o que ele faz. Continue indo.",
  "O sucesso não está no que você tem, mas em quem você é.",
  "Seu potencial é como uma semente; precisa de cuidados para crescer.",
  "Mantenha o comprometimento com suas metas, mas seja flexível na abordagem.",
];
// Chinese (Simplified)
const ChineseTextArray = [
  "今天就开始，不要等到明天。",
  "与你渴望成为的人为伍。",
  "摆脱生活中的负面影响。",
  "永远不要说 '我不能'。",
  "相信你的能力和潜力。",
  "每一小步都对巨大成就至关重要。",
  "把挑战看成是成长的机会。",
  "你的成功取决于你的日常习惯。",
  "从失败中汲取教训；它们是通往成功的台阶。",
  "设定明确的目标并坚决努力实现。",
  "成功不是目的地；它是一段旅程。",
  "保持专注于你的愿景，忽略干扰。",
  "庆祝你的进步，无论多么微小。",
  "冒险一试，不要畏惧走出舒适区。",
  "包围自己积极向上的人和事。",
  "你的态度决定你在生活中的高度。",
  "设想你的成功并朝着这个愿景努力。",
  "持续学习是保持领先的关键。",
  "成功是小小努力每日重复的总和。",
  "保持坚持不懈；成功通常在坚韧之后到来。",
  "相信连贯性的力量。",
  "挑战自己每天变得更好。",
  "不要害怕改变；拥抱它促进成长。",
  "成功不是运气；而是辛勤工作和奉献的结果。",
  "投资自我提升；你是最好的资产。",
  "环绕自己积极向上，抛弃消极。",
  "你的心态决定了你的人生高度。",
  "梦想大，努力工作，保持专注。",
  "成功是克服障碍的旅程。",
  "不要将你的第一章与别人的第二十章相比。",
  "保持对自己和价值观的忠诚。",
  "庆祝他人的成功；它会吸引积极性。",
  "保持适应性；变化是唯一不变的。",
  "你的潜力是无限的；相信自己。",
  "成功不在于目的地；而在于旅程。",
  "挑战自己超越极限。",
  "成功是准备、辛勤工作和学习的结果。",
  "创造一个让你早上想跳起床的愿景。",
  "你的时机就是现在；不要等待完美时刻。",
  "保持积极，努力工作，让它发生。",
  "每一次挫折都是一次回弹的准备。",
  "成功不是最终，失败也不是致命；勇气才是最重要的。",
  "对你的影响只受你想象和承诺的限制。",
  "梦想。相信。实现。",
  "你比想象中更坚强，更有能力。",
  "做伟大工作的唯一方法就是热爱自己的工作。",
  "不要看表；做它所做的。继续前进。",
  "成功不在于你拥有什么，而在于你是谁。",
  "你的潜力就像一颗种子；它需要精心呵护才能生长。",
  "对目标保持执着，但在方法上保持灵活性。",
];
// Japanese
const JapaneseTextArray = [
  "今日から始めよう、明日を待つのは遅い。",
  "あなたがなりたいと思う人々に囲まれましょう。",
  "あなたの人生からネガティブな影響を断ち切りましょう。",
  "決して '私はできない' と言わないでください。",
  "あなたの能力と可能性を信じてください。",
  "すべての小さなステップは大きな成就に貢献します。",
  "挑戦を成長の機会と見なしてください。",
  "あなたの成功は日常の習慣にかかっています。",
  "失敗から学ぶ；それらは成功への階段です。",
  "明確な目標を設定し、決意して取り組みましょう。",
  "成功は目的地ではなく、旅です。",
  "あなたのビジョンに集中し、邪魔を無視してください。",
  "進歩を祝福してください、どんなに小さくても。",
  "冒険し、快適なゾーンから出ることを恐れないでください。",
  "ポジティブで楽観的な人々に囲まれてください。",
  "あなたの態度が人生での高さを決定します。",
  "成功を想像し、そのビジョンに向けて努力してください。",
  "継続的な学習が先を行く鍵です。",
  "成功は小さな努力が毎日繰り返される結果です。",
  "持続力を保ちましょう；成功はしばしば忍耐の後に来ます。",
  "一貫性の力を信じてください。",
  "毎日良くなるように自分に挑戦してください。",
  "変化を恐れずに受け入れ、成長のためにそれを抱きましょう。",
  "成功は運ではなく、努力と献身の結果です。",
  "自己啓発に投資してください；あなたは最高の資産です。",
  "ポジティブなものに囲まれ、ネガティブなものを捨てましょう。",
  "あなたのマインドセットが結果を決定します。",
  "大きな夢を見て、一生懸命働いて、集中し続けてください。",
  "成功は障害を乗り越える旅です。",
  "あなたの第1章を他の人の第20章と比較しないでください。",
  "自分自身と自分の価値観に忠実でいましょう。",
  "他人の成功を祝福してください；それはポジティブなエネルギーを引き寄せます。",
  "適応力を持ちましょう；変化こそが唯一の定数です。",
  "あなたの可能性は無限です；自分を信じてください。",
  "成功は目的地ではなく、旅です。",
  "自分の限界を超えるように自分に挑戦してください。",
  "成功は準備、努力、学びの結果です。",
  "朝起きてベッドから飛び出したくなるビジョンを作りましょう。",
  "あなたの時間は今です；完璧な瞬間を待たないでください。",
  "前向きで、一生懸命働いて、それを実現させましょう。",
  "どんな逆境もカムバックの準備です。",
  "成功は最終的ではなく、失敗は致命的ではありません；それが勇気を持ち続けることが大切です。",
  "あなたの影響力の唯一の制限はあなたの想像力とコミットメントです。",
  "夢を見て、信じて、実現してください。",
  "あなたは自分が思っているよりも強く、想像以上にできる。",
  "素晴らしい仕事をする唯一の方法は、あなたの仕事を愛することです。",
  "時計を見ないでください；それがすることをしてください。続けましょう。",
  "成功はあなたが持っているものではなく、あなたが誰であるかにかかっています。",
  "あなたの可能性は種のようなものです；成長には育てる必要があります。",
  "目標には固執するが、アプローチでは柔軟性を保ちましょう。",
];
// Indian
const HindiTextArray = [
  "आज से ही शुरू करें, कल का इंतजार मत करें।",
  "उन लोगों के साथ रहें जिन्हें आप बनना चाहते हैं।",
  "अपने जीवन से नकारात्मक प्रभावों को काट लें।",
  "कभी भी 'मैं नहीं कर सकता' ना कहें।",
  "अपनी क्षमताओं और संभावनाओं में विश्वास करें।",
  "हर छोटे कदम का महत्वपूर्ण योगदान है।",
  "चुनौती को विकास के अवसर के रूप में देखें।",
  "आपकी सफलता आपके दैनिक आदतों पर निर्भर करती है।",
  "असफलता से सिखें; ये सफलता की सीढ़ियों की ओर कदम रखती हैं।",
  "स्पष्ट लक्ष्य निर्धारित करें और उन पर कड़ाई से काम करें।",
  "सफलता एक गंतव्य नहीं, एक यात्रा है।",
  "अपने दृष्टिकोण पर केंद्रित रहें और अफसोस को अनदेखा करें।",
  "आपकी प्रगति को मनाएं, चाहे वह कितनी भी छोटी क्यों ना हो।",
  "जोखिम उठाएं, और अपने सीमा क्षेत्र से बाहर जाने से नहीं डरें।",
  "खुद को सकारात्मक लोगों और वस्तुओं के साथ घेरें।",
  "आपका दृष्टिकोण आपके जीवन में ऊचाई का निर्धारण करता है।",
  "अपनी सफलता की ख़्वाहिश करें और उस दृष्टिकोण की दिशा में काम करें।",
  "निरंतर शिक्षा होना आगे बढ़ने का कुंजी है।",
  "सफलता छोटे प्रयासों के दैनिक आवृत्ति का ही योग है।",
  "दृढ़ता बनाए रखें; सफलता अक्सर सहनशीलता के बाद आती है।",
  "सहिष्णुता की शक्ति में विश्वास रखें।",
  "अपने आप को हर दिन बेहतर बनाने के लिए खुद से चुनौती दें।",
  "परिवर्तन से नहीं डरें; विकास के लिए इसे अपनाएं।",
  "सफलता भाग्य के बारे में नहीं है; यह मेहनत और समर्पण के बारे में है।",
  "आत्म-सुधार में निवेश करें; आप अपनी सर्वोत्तम संपत्ति हैं।",
  "सकारात्मकता में अपने आत्मविश्वास को बढ़ाएं और नकारात्मकता को छोड़ दें।",
  "आपका मानसिकता आपके जीवन में उच्चता का निर्धारण करती है।",
  "बड़े सपने देखें, कड़ी मेहनत करें, ध्यान लगाए रखें।",
  "सफलता अवस्थाओं को पार करने की यात्रा है।",
  "अपने अध्याय 1 को किसी और के अध्याय 20 से तुलना न करें।",
  "अपने आत्मविश्वास और मूल्यों के प्रति सच्चे रहें।",
  "दूसरों की सफलता का उत्सव करें; यह सकारात्मकता को आकर्षित करता है।",
  "अनुकूलता में रहें; परिवर्तन ही एकमात्र स्थिर चीज है।",
  "आपकी संभावना असीमित है; अपने आप पर विश्वास करें।",
  "सफलता गंतव्य के बारे में नहीं, यह एक यात्रा है।",
  "अपनी सीमाओं को पार करने के लिए खुद से चुनौती दें।",
  "सफलता पूर्वयापी, कड़ी मेहनत, और सीखने का परिणाम है।",
  "एक विजन बनाएं जो आपको सुबह बेड से बाहर उछलने के लिए उत्साहित करता है।",
  "आपका समय अब है; सवाइट के लिए पूर्ण क्षण का इंतजार न करें।",
  "सकारात्मक रहें, कड़ी मेहनत करें, इसे होने दें।",
  "चाहे जो भी प्रतिबंध हो, यह एक कमबैक के लिए तैयारी है।",
  "सफलता सत्ताई नहीं है, असफलता घातक नहीं है; यह जारी रखने का साहस है।",
  "आपके प्रभाव की एकमात्र सीमा आपकी कल्पना और प्रतिबद्धता पर निर्भर करती है।",
  "सपना देखें। विश्वास करें। हासिल करें।",
  "आप उससे भी शक्तिशाली हैं जितना आप सोचते हैं, जितना आपकी कल्पना कर सकते हैं।",
  "श्रेष्ठ काम करने का एकमात्र तरीका वह है कि आप जो काम करना चाहते हैं, वह प्यार करें।",
  "घड़ी को न देखें; वह क्या करती है। जारी रखें।",
  "सफलता यह नहीं है कि आपके पास क्या है, बल्कि आप कौन हैं।",
  "आपकी संभावना एक बीज की तरह है; इसे बढ़ावा देने की आवश्यकता है।",
  "अपने लक्ष्यों के प्रति दृढ़ता बनाए रखें, लेकिन अपने दृष्टिकोण में लचीलाई बनाए रखें।",
];
// Urdu
const UrduTextArray = [
  "آج ہی شروع کریں، کل کا انتظار نہ کریں۔",
  "اپنی زندگی کو بہتر بنانے والوں کے گرد خود کو گھیر لیں۔",
  "منفی اثرات کو اپنی زندگی سے نکال دیں۔",
  "کبھی نہ کہیں 'میں نہیں کر سکتا۔'",
  "اپنی صلاحیتوں اور پتنشنل میں یقین رکھیں۔",
  "ہر چھوٹا قدم بڑے حصول تک کا راستہ ہوتا ہے۔",
  "چیلنجز کو بڑھانے کا موقع سمجھیں۔",
  "آپ کی کامیابی آپ کی روزانہ کی عادات پر مبنی ہوتی ہے۔",
  "ناکامیوں سے سیکھیں؛ یہ کامیابی کے راستے ہیں۔",
  "واضح مقاصد مرتب کریں اور اس راستے پر مصممیت کے ساتھ کام کریں۔",
  "کامیابی منزل نہیں، یہ سفر ہے۔",
  "اپنی منظر کو مرکوز رکھیں اور چٹخوں کو نظر انداز کریں۔",
  "اپنی پیشرفت کی تشہیر کریں، چاہے وہ کتنی ہی چھوٹی ہو۔",
  "جوخودی کو دھوکہ دے، اور اپنے اہم شرح میں نہ رہے۔",
  "خود پرستی اور مثبت لوگوں کے گرد گھیریں۔",
  "آپ کی رویہ کو زندگی کی بلندی میں اثر انداز کرتا ہے۔",
  "اپنی کامیابی کو تصویر بنائیں اور اس وژن کی طرف بڑھیں۔",
  "مستقل سیکھنا آگے رہنے کا راز ہے۔",
  "کامیابی چھوٹے پریشانیوں کے دہرانے میں ہے۔",
  "استمرار کے بعد زیادہ تر کامیابی آتی ہے۔",
  "استقلال کی طاقت میں یقین رکھیں۔",
  "خود کو ہر روز بہتر بنانے کے لئے خود کو چیلنج دیں۔",
  "تبدیلی سے نہیں ڈریں؛ بڑھائیں تاکہ بڑھائیں۔",
  "کامیابی حظ کے بارے میں نہیں، بلکہ محنت اور عہد کے بارے میں ہے۔",
  "خود سدھار میں سرمایہ گاری کریں؛ آپ خود اپنا بہترین دارائی ہیں۔",
  "پابندگی سے خود کو اپنے لکیر میں رکھیں۔",
  "مثبتیت کے ساتھ گرد گھیریں اور منفیتوں کو چھوڑ دیں۔",
  "آپ کی رویہ آپ کی بلندی کو طے کرتی ہے۔",
  "بڑا سوچیں، محنت کریں، مرکوز رہیں۔",
  "کامیابی رکاوٹوں کو پار کرنے کا نتیجہ ہوتی ہے۔",
  "اپنی پہلی چھپائی کو کسی کے بیسواہ چھپائی سے موازنہ نہ کریں۔",
  "اپنی حقیقت اور اپنے اصولوں پر قائم رہیں۔",
  "دوسروں کی کامیابی کی تعریف کریں؛ یہ خوشیاں کھینچتی ہے۔",
  "لازمی ہے؛ تبدیلی ہی واقعی ہے۔",
  "آپ کی پتنشنل بے حد ہے؛ خود پر یقین رکھیں۔",
  "کامیابی منزل کے بارے میں نہیں، بلکہ سفر کے بارے میں ہے۔",
  "اپنے حدوں سے بہتر بننے کے لئے خود کو چیلنج دیں۔",
  "کامیابی نتیجہ، محنت اور سیکھنے کا نتیجہ ہے۔",
  "ایک وژن بنائیں جو آپ کو صبح بیڈ سے باہر نکلنے پر مجبور کرتا ہے۔",
  "آپ کا وقت اب ہے؛ پرفیکٹ لمحے کا انتظار نہ کریں۔",
  "مثبت رہیں، محنت کریں، یہ ممکن ہوگا۔",
  "ہر رکاوٹ ایک کمبیک کی تیاری کا حصہ ہے۔",
  "کامیابی فائنل نہیں، ناکامی آخری نہیں ہوتی؛ یہ جاری رہنے کا حسینی ہے۔",
  "آپ کی اثرات کی کمی میں آپ کی خیالات اور عہد پر مبنی ہے۔",
  "آپ کا وقت محدود ہے؛ پرفیکٹ لمحے کا انتظار نہ کریں۔",
];
// Korean
const KoreanTextArray = [
  "오늘 시작하십시오. 내일을 기다리지 마십시오.",
  "당신이 되고 싶어하는 사람들과 어울리세요.",
  "인생에서 부정적인 영향을 차단하세요.",
  "'나는 할 수 없다'라고 말하지 마세요.",
  "당신의 능력과 잠재력을 믿으세요.",
  "작은 한 걸음이 큰 성취로 이어집니다.",
  "도전을 기회로 받아들이세요.",
  "성공은 일상적인 습관의 합산입니다.",
  "실패에서 배우세요; 그것은 성공으로 가는 발판입니다.",
  "목표를 명확하게 설정하고 결실을 맺도록 노력하세요.",
  "성공은 목적지가 아니라 여정입니다.",
  "자신의 비전에 집중하고 방해 요소를 무시하세요.",
  "작은 성과도 축하하세요, 어떻게 작더라도.",
  "위험을 감수하고 안전 지대를 벗어나지 마세요.",
  "긍정적이고 낙관적인 사람들에게 둘러싸이세요.",
  "당신의 태도가 삶에서의 높이를 결정합니다.",
  "성공을 시각화하고 그 비전을 향해 나아가세요.",
  "계속해서 학습하는 것이 앞서 나가는 열쇠입니다.",
  "성공은 일상적인 노력의 합입니다.",
  "인내심을 유지하십시오; 성공은 종종 인내 뒤에 나옵니다.",
  "일관성의 힘을 믿으세요.",
  "매일 더 나은 자신이 되기 위해 도전하세요.",
  "변화를 두려워하지 마세요; 성장을 위해 받아들이세요.",
  "성공은 운이 아니라 노력과 헌신의 결과입니다.",
  "자기 개발에 투자하세요; 당신은 최고의 자산입니다.",
  "긍정적이고 부정적인 것을 놓아두세요.",
  "당신의 마음가짐이 결과를 결정합니다.",
  "큰 꿈을 꾸고 열심히 일하세요.",
  "성공은 어려움을 극복한 여정입니다.",
  "자신의 1장을 남의 20장과 비교하지 마세요.",
  "자신과 가치관에 충실하세요.",
  "다른 사람들의 성공을 축하하세요; 그것은 긍정적인 에너지를 끌어들입니다.",
  "적응할 수 있으세요; 변화는 유일한 상수입니다.",
  "당신의 잠재력은 무한합니다; 자신을 믿으세요.",
  "성공은 목적지가 아니라 여정입니다.",
  "자신의 한계를 넘어 도전하세요.",
  "성공은 준비, 노력, 학습의 결과입니다.",
  "아침에 누우는 걸 원하는 비전을 만드세요.",
  "당신의 시간은 지금입니다; 완벽한 순간을 기다리지 마세요.",
  "긍정적으로 생각하고 열심히 일하세요.",
  "모든 좌절은 반듯이 반듯이 부활의 기회입니다.",
  "성공은 영원하지 않으며, 실패는 영원하지 않습니다; 계속되는 용기가 중요합니다.",
  "당신의 영향력의 한계는 상상력과 헌신에 달려 있습니다.",
  "꿈을 꾸고, 믿고, 달성하세요.",
  "당신은 생각보다 강하고 상상보다 능력있습니다.",
  "큰성공을 위해 당신이 하는 일을 사랑하세요.",
  "시계를 보지 말고, 시계가 하는 일처럼 행동하세요.",
  "성공은 당신이 가지고 있는 것이 아니라, 당신이 누구냐에 달려 있습니다.",
  "당신의 잠재력은 씨앗과 같습니다; 성장을 위해 기를 필요로 합니다.",
  "목표에 헌신하되 방법에는 융통성을 유지하세요.",
];
