let IconsSrc = {
  PreLoaderGif: {
    Dark: "Icons/PreLoader/DarkPreLoader.gif",
    Light: "Icons/PreLoader/LightPreLoader.gif",
    Neon: "Icons/PreLoader/PreLoadGif.gif",
  },
  AddNotesIcon: {
    Dark: "Icons/DarkIcons/AddNotesIcon.png",
    Light: "Icons/LightIcons/AddNotesIcon.png",
    Neon: "Icons/NeonIcons/AddNotesIcon.png",
  },
  MoonIcon: {
    Dark: "Icons/DarkIcons/MoonIcon.png",
    Light: "Icons/LightIcons/MoonIcon.png",
    Neon: "Icons/NeonIcons/MoonIcon.png",
  },
  SunIcon: {
    Dark: "Icons/DarkIcons/SunIcon.png",
    Light: "Icons/LightIcons/SunIcon.png",
    Neon: "Icons/NeonIcons/SunIcon.png",
  },
  EmptyBoxIcon: {
    Dark: "Icons/DarkIcons/EmptyIcon.png",
    Light: "Icons/LightIcons/EmptyIcon.png",
    Neon: "Icons/NeonIcons/EmptyIcon.png",
  },
  NoResultFoundIcon: {
    Dark: "Icons/DarkIcons/NoResultFoundIcon.png",
    Light: "Icons/LightIcons/NoResultFoundIcon.png",
    Neon: "Icons/NeonIcons/NoResultFoundIcon.png",
  },
  UpArrowIcon: {
    Dark: "Icons/DarkIcons/UpArrowIcon.png",
    Light: "Icons/LightIcons/UpArrowIcon.png",
    Neon: "Icons/NeonIcons/UpArrowIcon.png",
  },
  DownArrowIcon: {
    Dark: "Icons/DarkIcons/DownArrowIcon.png",
    Light: "Icons/LightIcons/DownArrowIcon.png",
    Neon: "Icons/NeonIcons/DownArrowIcon.png",
  },
  LeftArrowIcon: {
    Dark: "Icons/DarkIcons/LeftArrowIcon.png",
    Light: "Icons/LightIcons/LeftArrowIcon.png",
    Neon: "Icons/NeonIcons/LeftArrowIcon.png",
  },
  RightArrowIcon: {
    Dark: "Icons/DarkIcons/RightArrowIcon.png",
    Light: "Icons/LightIcons/RightArrowIcon.png",
    Neon: "Icons/NeonIcons/RightArrowIcon.png",
  },
  SeperatorIcon: {
    Dark: "Icons/DarkIcons/SeperatorIcon.png",
    Light: "Icons/LightIcons/SeperatorIcon.png",
    Neon: "Icons/NeonIcons/SeperatorIcon.png",
  },
};
let CategoryColors = [
  { Name: "Green", ID: "green-pallet", Color: "#40C057" },
  { Name: "Blue", ID: "blue-pallet", Color: "#008FFD" },
  { Name: "Red", ID: "red-pallet", Color: "#FF4545" },
  { Name: "Purple", ID: "purple-pallet", Color: "#7c73e6" },
  { Name: "Sage Green", ID: "sage-green-pallet", Color: "#A3B18A" },
  { Name: "Dusty Rose", ID: "dusty-rose-pallet", Color: "#C09DA0" },
  { Name: "Muted Gold", ID: "muted-gold-pallet", Color: "#C8B580" },
  { Name: "Earthy Brown", ID: "earthy-brown-pallet", Color: "#927B6E" },
  { Name: "Soft Lavender", ID: "soft-lavender-pallet", Color: "#B9A8C9" },
  { Name: "Faded Coral", ID: "faded-coral-pallet", Color: "#D4A7A5" },
  { Name: "Vintage Blue", ID: "vintage-blue-pallet", Color: "#8494AB" },
  { Name: "Worn Olive", ID: "worn-olive-pallet", Color: "#A6A375" },
  { Name: "Dull Teal", ID: "dull-teal-pallet", Color: "#6F8D8A" },
  { Name: "Old Rose", ID: "old-rose-pallet", Color: "#B3949D" },
  { Name: "Muted Turquoise", ID: "muted-turquoise-pallet", Color: "#6D9EA5" },
  { Name: "Antique Mauve", ID: "antique-mauve-pallet", Color: "#BDA3B2" },
  { Name: "Washed Denim", ID: "washed-denim-pallet", Color: "#7D92A3" },
  { Name: "Subtle Peach", ID: "subtle-peach-pallet", Color: "#E2B9A1" },
  { Name: "Desert Sand", ID: "desert-sand-pallet", Color: "#D4C0A1" },
  { Name: "Faded Plum", ID: "faded-plum-pallet", Color: "#876477" },
  { Name: "Soft Moss", ID: "soft-moss-pallet", Color: "#7E8B6A" },
  { Name: "Aged Brick", ID: "aged-brick-pallet", Color: "#9E7E78" },
  { Name: "Stone Grey", ID: "stone-grey-pallet", Color: "#B3B8A2" },
  { Name: "Weathered Sky", ID: "weathered-sky-pallet", Color: "#A9B7C6" },
];
let CategoryIcons = [
  { ID: "CategoryIcon-123456789", Source: `Icons/CategoryIcons/basketball-svgrepo-com.svg` },
  { ID: "CategoryIcon-234567891", Source: `Icons/CategoryIcons/book-opened-svgrepo-com.svg` },
  { ID: "CategoryIcon-345678912", Source: `Icons/CategoryIcons/bulp-lamp-off-svgrepo-com.svg` },
  { ID: "CategoryIcon-456789123", Source: `Icons/CategoryIcons/bulp-lamp-on-svgrepo-com.svg` },
  { ID: "CategoryIcon-567891234", Source: `Icons/CategoryIcons/calendar-svgrepo-com.svg` },
  { ID: "CategoryIcon-891234567", Source: `Icons/CategoryIcons/car-svgrepo-com.svg` },
  { ID: "CategoryIcon-912345678", Source: `Icons/CategoryIcons/cel-reindeer-svgrepo-com.svg` },
  { ID: "CategoryIcon-123456890", Source: `Icons/CategoryIcons/cel-snow-globe-svgrepo-com.svg` },
  { ID: "CategoryIcon-234567901", Source: `Icons/CategoryIcons/cld-cloud-network-folder-svgrepo-com.svg` },
  { ID: "CategoryIcon-345678912", Source: `Icons/CategoryIcons/cld-server-svgrepo-com.svg` },
  { ID: "CategoryIcon-456789123", Source: `Icons/CategoryIcons/cle-peg-svgrepo-com.svg` },
  { ID: "CategoryIcon-567891234", Source: `Icons/CategoryIcons/cle-wash-basin-svgrepo-com.svg` },
  { ID: "CategoryIcon-678912345", Source: `Icons/CategoryIcons/clock-svgrepo-com.svg` },
  { ID: "CategoryIcon-789123456", Source: `Icons/CategoryIcons/cloud-svgrepo-com.svg` },
  { ID: "CategoryIcon-891234567", Source: `Icons/CategoryIcons/com-laptop-code-svgrepo-com.svg` },
  { ID: "CategoryIcon-912345678", Source: `Icons/CategoryIcons/cross-hair-svgrepo-com.svg` },
  { ID: "CategoryIcon-123456890", Source: `Icons/CategoryIcons/dashboard-svgrepo-com.svg` },
  { ID: "CategoryIcon-234567901", Source: `Icons/CategoryIcons/des-protractor-svgrepo-com.svg` },
  { ID: "CategoryIcon-345678912", Source: `Icons/CategoryIcons/envelope-svgrepo-com.svg` },
  { ID: "CategoryIcon-456789123", Source: `Icons/CategoryIcons/filmstrip-svgrepo-com.svg` },
  { ID: "CategoryIcon-567891234", Source: `Icons/CategoryIcons/headphones-svgrepo-com.svg` },
  { ID: "CategoryIcon-678912345", Source: `Icons/CategoryIcons/heart-check-svgrepo-com.svg` },
  { ID: "CategoryIcon-789123456", Source: `Icons/CategoryIcons/imac-svgrepo-com.svg` },
  { ID: "CategoryIcon-891234567", Source: `Icons/CategoryIcons/iphone-svgrepo-com.svg` },
  { ID: "CategoryIcon-912345678", Source: `Icons/CategoryIcons/leaf-svgrepo-com.svg` },
  { ID: "CategoryIcon-123456890", Source: `Icons/CategoryIcons/macbook-pro-svgrepo-com.svg` },
  { ID: "CategoryIcon-234567901", Source: `Icons/CategoryIcons/med-kit-svgrepo-com.svg` },
  { ID: "CategoryIcon-345678912", Source: `Icons/CategoryIcons/pencil-svgrepo-com.svg` },
  { ID: "CategoryIcon-456789123", Source: `Icons/CategoryIcons/phone-rotary-svgrepo-com.svg` },
  { ID: "CategoryIcon-567891234", Source: `Icons/CategoryIcons/photo-camera-svgrepo-com.svg` },
  { ID: "CategoryIcon-678912345", Source: `Icons/CategoryIcons/piano-svgrepo-com.svg` },
  { ID: "CategoryIcon-789123456", Source: `Icons/CategoryIcons/price-tag-svgrepo-com.svg` },
  { ID: "CategoryIcon-891234567", Source: `Icons/CategoryIcons/rocket-svgrepo-com.svg` },
  { ID: "CategoryIcon-912345678", Source: `Icons/CategoryIcons/shopping-card-svgrepo-com.svg` },
  { ID: "CategoryIcon-123456890", Source: `Icons/CategoryIcons/star-svgrepo-com.svg` },
  { ID: "CategoryIcon-234567901", Source: `Icons/CategoryIcons/sun-svgrepo-com.svg` },
  { ID: "CategoryIcon-345678912", Source: `Icons/CategoryIcons/tree-decidious-svgrepo-com.svg` },
  { ID: "CategoryIcon-456789123", Source: `Icons/CategoryIcons/tree-evergreen-svgrepo-com.svg` },
  { ID: "CategoryIcon-567891234", Source: `Icons/CategoryIcons/trophy-svgrepo-com.svg` },
  { ID: "CategoryIcon-678912345", Source: `Icons/CategoryIcons/woman-svgrepo-com.svg` },
  { ID: "CategoryIcon-789123456", Source: `Icons/CategoryIcons/wrench-svgrepo-com.svg` },
];
