let HoverColor = {
  Dark: "#40C057",
  Light: "#ffc069",
  Neon: "",
};
let IconsSrc = {
  PreLoaderGif: {
    Dark: "Icons/PreLoader/DarkPreLoader.gif",
    Light: "Icons/PreLoader/LightPreLoader.gif",
    Neon: "Icons/PreLoader/PreLoadGif.gif",
  },
  HomeIcon: {
    Dark: "Icons/DarkIcons/HomeIcon.png",
    Light: "Icons/LightIcons/HomeIcon.png",
    Neon: "Icons/NeonIcons/HomeIcon.png",
  },
  NewTaskIcon: {
    Dark: "Icons/DarkIcons/NewTaskIcon.png",
    Light: "Icons/LightIcons/NewTaskIcon.png",
    Neon: "Icons/NeonIcons/NewTaskIcon.png",
  },
  NewCategoryIcon: {
    Dark: "Icons/DarkIcons/NewCategoryIcon.png",
    Light: "Icons/LightIcons/NewCategoryIcon.png",
    Neon: "Icons/NeonIcons/NewCategoryIcon.png",
  },
  CalendarIcon: {
    Dark: "Icons/DarkIcons/CalendarIcon.png",
    Light: "Icons/LightIcons/CalendarIcon.png",
    Neon: "Icons/NeonIcons/CalendarIcon.png",
  },
  MyNotesIcon: {
    Dark: "Icons/DarkIcons/NotesIcon.png",
    Light: "Icons/LightIcons/NotesIcon.png",
    Neon: "Icons/NeonIcons/NotesIcon.png",
  },
  AddNotesIcon: {
    Dark: "Icons/DarkIcons/AddNotesIcon.png",
    Light: "Icons/LightIcons/AddNotesIcon.png",
    Neon: "Icons/NeonIcons/AddNotesIcon.png",
  },
  MyAlarmsIcon: {
    Dark: "Icons/DarkIcons/AlarmsIcon.png",
    Light: "Icons/LightIcons/AlarmsIcon.png",
    Neon: "Icons/NeonIcons/AlarmsIcon.png",
  },
  SettingsIcon: {
    Dark: "Icons/DarkIcons/SettingsIcon.png",
    Light: "Icons/LightIcons/SettingsIcon.png",
    Neon: "Icons/NeonIcons/SettingsIcon.png",
  },
  CloseIcon: {
    Dark: "Icons/DarkIcons/CrossSign.png",
    Light: "Icons/LightIcons/CrossSign.png",
    Neon: "Icons/NeonIcons/CrossSign.png",
  },
  SelectIcon: {
    Dark: "Icons/DarkIcons/SelectIcon.png",
    Light: "Icons/LightIcons/SelectIcon.png",
    Neon: "Icons/NeonIcons/SelectIcon.png",
  },
  DeselctIcon: {
    Dark: "Icons/DarkIcons/DeSelectIcon.png",
    Light: "Icons/LightIcons/DeSelectIcon.png",
    Neon: "Icons/NeonIcons/DeSelectIcon.png",
  },
  PinIcon: {
    Dark: "Icons/DarkIcons/PinIcon.png",
    Light: "Icons/LightIcons/PinIcon.png",
    Neon: "Icons/NeonIcons/PinIcon.png",
  },
  UnPinIcon: {
    Dark: "Icons/DarkIcons/UnPinIcon.png",
    Light: "Icons/LightIcons/UnPinIcon.png",
    Neon: "Icons/NeonIcons/UnPinIcon.png",
  },
  TodayIcon: {
    Dark: "Icons/DarkIcons/TodayIcon.png",
    Light: "Icons/LightIcons/TodayIcon.png",
    Neon: "Icons/NeonIcons/TodayIcon.png",
  },
  NextDayIcon: {
    Dark: "Icons/DarkIcons/NextDayIcon.png",
    Light: "Icons/LightIcons/NextDayIcon.png",
    Neon: "Icons/NeonIcons/NextDayIcon.png",
  },
  PreviousDayIcon: {
    Dark: "Icons/DarkIcons/PreviousDayIcon.png",
    Light: "Icons/LightIcons/PreviousDayIcon.png",
    Neon: "Icons/NeonIcons/PreviousDayIcon.png",
  },
  EditIcon: {
    Dark: "Icons/DarkIcons/EditIcon.png",
    Light: "Icons/LightIcons/EditIcon.png",
    Neon: "Icons/NeonIcons/EditIcon.png",
  },
  DeleteIcon: {
    Dark: "Icons/DarkIcons/CrossSign.png",
    Light: "Icons/LightIcons/CrossSign.png",
    Neon: "Icons/NeonIcons/CrossSign.png",
  },
  TrashIcon: {
    Dark: "Icons/DarkIcons/TrashBinIcon.png",
    Light: "Icons/LightIcons/TrashBinIcon.png",
    Neon: "Icons/NeonIcons/TrashBinIcon.png",
  },
  CompleteIcon: {
    Dark: "Icons/DarkIcons/DoneIcon.png",
    Light: "Icons/LightIcons/DoneIcon.png",
    Neon: "Icons/NeonIcons/DoneIcon.png",
  },
  FailIcon: {
    Dark: "Icons/DarkIcons/FailedIcon.png",
    Light: "Icons/LightIcons/FailedIcon.png",
    Neon: "Icons/NeonIcons/FailedIcon.png",
  },
  RestoreIcon: {
    Dark: "Icons/DarkIcons/RestoreIcon.png",
    Light: "Icons/LightIcons/RestoreIcon.png",
    Neon: "Icons/NeonIcons/RestoreIcon.png",
  },
  GenerateBackupIcon: {
    Dark: "Icons/DarkIcons/GenerateBackUpIcon.png",
    Light: "Icons/LightIcons/GenerateBackUpIcon.png",
    Neon: "Icons/NeonIcons/GenerateBackUpIcon.png",
  },
  CloudStorgeIcon: {
    Dark: "Icons/DarkIcons/CloudStorgeIcon.png",
    Light: "Icons/LightIcons/CloudStorgeIcon.png",
    Neon: "Icons/NeonIcons/CloudStorgeIcon.png",
  },
  MoonIcon: {
    Dark: "Icons/DarkIcons/MoonIcon.png",
    Light: "Icons/LightIcons/MoonIcon.png",
    Neon: "Icons/NeonIcons/MoonIcon.png",
  },
  SunIcon: {
    Dark: "Icons/DarkIcons/SunIcon.png",
    Light: "Icons/LightIcons/SunIcon.png",
    Neon: "Icons/NeonIcons/SunIcon.png",
  },
  PaperClipIcon: {
    Dark: "Icons/DarkIcons/PaperClipIcon.png",
    Light: "Icons/LightIcons/PaperClipIcon.png",
    Neon: "Icons/NeonIcons/PaperClipIcon.png",
  },
  EmptyBoxIcon: {
    Dark: "Icons/DarkIcons/EmptyIcon.png",
    Light: "Icons/LightIcons/EmptyIcon.png",
    Neon: "Icons/NeonIcons/EmptyIcon.png",
  },
  UpArrowIcon: {
    Dark: "Icons/DarkIcons/UpArrowIcon.png",
    Light: "Icons/LightIcons/UpArrowIcon.png",
    Neon: "Icons/NeonIcons/UpArrowIcon.png",
  },
  DownArrowIcon: {
    Dark: "Icons/DarkIcons/DownArrowIcon.png",
    Light: "Icons/LightIcons/DownArrowIcon.png",
    Neon: "Icons/NeonIcons/DownArrowIcon.png",
  },
  LeftArrowIcon: {
    Dark: "Icons/DarkIcons/LeftArrowIcon.png",
    Light: "Icons/LightIcons/LeftArrowIcon.png",
    Neon: "Icons/NeonIcons/LeftArrowIcon.png",
  },
  RightArrowIcon: {
    Dark: "Icons/DarkIcons/RightArrowIcon.png",
    Light: "Icons/LightIcons/RightArrowIcon.png",
    Neon: "Icons/NeonIcons/RightArrowIcon.png",
  },
  SeperatorIcon: {
    Dark: "Icons/DarkIcons/SeperatorIcon.png",
    Light: "Icons/LightIcons/SeperatorIcon.png",
    Neon: "Icons/NeonIcons/SeperatorIcon.png",
  },
};
let CategoryColors = [
  { Name: "Green", ID: "green-pallet", Color: "#40C057" },
  { Name: "Blue", ID: "blue-pallet", Color: "#008FFD" },
  { Name: "Red", ID: "red-pallet", Color: "#FF4545" },
  { Name: "Purple", ID: "purple-pallet", Color: "#7c73e6" },
  { Name: "Sage Green", ID: "sage-green-pallet", Color: "#A3B18A" },
  { Name: "Dusty Rose", ID: "dusty-rose-pallet", Color: "#C09DA0" },
  { Name: "Muted Gold", ID: "muted-gold-pallet", Color: "#C8B580" },
  { Name: "Earthy Brown", ID: "earthy-brown-pallet", Color: "#927B6E" },
  { Name: "Soft Lavender", ID: "soft-lavender-pallet", Color: "#B9A8C9" },
  { Name: "Faded Coral", ID: "faded-coral-pallet", Color: "#D4A7A5" },
  { Name: "Vintage Blue", ID: "vintage-blue-pallet", Color: "#8494AB" },
  { Name: "Worn Olive", ID: "worn-olive-pallet", Color: "#A6A375" },
  { Name: "Dull Teal", ID: "dull-teal-pallet", Color: "#6F8D8A" },
  { Name: "Old Rose", ID: "old-rose-pallet", Color: "#B3949D" },
  { Name: "Muted Turquoise", ID: "muted-turquoise-pallet", Color: "#6D9EA5" },
  { Name: "Antique Mauve", ID: "antique-mauve-pallet", Color: "#BDA3B2" },
  { Name: "Washed Denim", ID: "washed-denim-pallet", Color: "#7D92A3" },
  { Name: "Subtle Peach", ID: "subtle-peach-pallet", Color: "#E2B9A1" },
  { Name: "Desert Sand", ID: "desert-sand-pallet", Color: "#D4C0A1" },
  { Name: "Faded Plum", ID: "faded-plum-pallet", Color: "#876477" },
  { Name: "Soft Moss", ID: "soft-moss-pallet", Color: "#7E8B6A" },
  { Name: "Aged Brick", ID: "aged-brick-pallet", Color: "#9E7E78" },
  { Name: "Stone Grey", ID: "stone-grey-pallet", Color: "#B3B8A2" },
  { Name: "Weathered Sky", ID: "weathered-sky-pallet", Color: "#A9B7C6" },
];
let CategoryIcons = [
  { Name: "BussinessIcon1", ID: "bussiness-icon1-button", Source: `Icons/CategoryIcons/BussinessIcon1.png` },
  { Name: "BussinessIcon2", ID: "bussiness-icon2-button", Source: `Icons/CategoryIcons/BussinessIcon2.png` },
  { Name: "ChoreIcon", ID: "chore-icon-button", Source: `Icons/CategoryIcons/ChoreIcon.png` },
  { Name: "FutureIcon", ID: "future-icon-button", Source: `Icons/CategoryIcons/FutureIcon.png` },
  { Name: "GameIcon", ID: "game-icon-button", Source: `Icons/CategoryIcons/GameIcon.png` },
  { Name: "ProgrammingIcon1", ID: "programming-icon-button", Source: `Icons/CategoryIcons/ProgrammingIcon.png` },
  { Name: "ProgrammingIcon2", ID: "programming-icon2-button", Source: `Icons/CategoryIcons/ProgrammingIcon2.png` },
  { Name: "FlightIcon", ID: "flight-icon-button", Source: `Icons/CategoryIcons/FlightIcon.png` },
  { Name: "PlanIcon", ID: "plan-icon-button", Source: `Icons/CategoryIcons/PlanIcon.png` },
  { Name: "CampingIcon", ID: "camping-icon-button", Source: `Icons/CategoryIcons/CampingIcon.png` },
  { Name: "SportIcon1", ID: "sport-icon1-button", Source: `Icons/CategoryIcons/SportIcon1.png` },
  { Name: "SportIcon2", ID: "sport-icon2-button", Source: `Icons/CategoryIcons/SportIcon2.png` },
  { Name: "MeetingIcon", ID: "meeting-icon-button", Source: `Icons/CategoryIcons/MeetingIcon.png` },
  { Name: "ShoppingIcon", ID: "shopping-icon-button", Source: `Icons/CategoryIcons/ShoppingIcon.png` },
  { Name: "StudyIcon", ID: "study-icon-button", Source: `Icons/CategoryIcons/StudyIcon.png` },
  { Name: "UniversityIcon", ID: "university-icon-button", Source: `Icons/CategoryIcons/UniversityIcon.png` },
  { Name: "VacationIcon", ID: "vacation-icon-button", Source: `Icons/CategoryIcons/VacationIcon.png` },
  { Name: "WorkIcon", ID: "work-icon-button", Source: `Icons/CategoryIcons/WorkIcon.png` },
];
